import type { CarouselCard } from "./types";

export const mockCards: CarouselCard[] = [
  {
    id: 1,
    title: "3XD",
    subtitle: "#FSADADS",
    price: "£4,444.00",
    pricePeriod: "/yr",
    progress: 15,
    verified: true,
    gradient: "from-violet-400 to-purple-600",
    description:
      "Spacious 3-bedroom detached property with a south-facing garden, recently renovated kitchen and two en-suite bathrooms. Ideal for families.",
    tags: ["Detached", "3 Bed", "Garden"],
  },
  {
    id: 2,
    title: "7BK",
    subtitle: "#PLQWERT",
    price: "£2,150.00",
    pricePeriod: "/yr",
    progress: 45,
    verified: true,
    gradient: "from-purple-500 to-indigo-600",
  },
  {
    id: 3,
    title: "9WR",
    subtitle: "#HNBVCXZ",
    price: "£6,800.00",
    pricePeriod: "/yr",
    progress: 72,
    verified: false,
    gradient: "from-fuchsia-500 to-purple-700",
    description:
      "Modern city-centre flat with floor-to-ceiling windows and an open-plan living area. Walking distance to public transport and shops.",
    tags: ["Flat", "City Centre", "Modern", "Transport Links"],
  },
  {
    id: 4,
    title: "1AZ",
    subtitle: "#TYGHJKL",
    price: "£3,320.00",
    pricePeriod: "/yr",
    progress: 30,
    verified: true,
    gradient: "from-violet-500 to-purple-800",
    description: "Cosy studio with allocated parking.",
  },
  {
    id: 5,
    title: "5MN",
    subtitle: "#WSDERFG",
    price: "£8,900.00",
    pricePeriod: "/yr",
    progress: 90,
    verified: false,
    gradient: "from-purple-400 to-violet-700",
    description:
      "Luxury penthouse suite with panoramic views across the harbour. Features a private rooftop terrace, wine cellar, and concierge service. Premium finishes throughout including Italian marble and smart-home automation.",
    tags: ["Penthouse", "Luxury", "Harbour View", "Rooftop", "Smart Home"],
  },
  {
    id: 6,
    title: "2QP",
    subtitle: "#LKJHGFD",
    price: "£1,750.00",
    pricePeriod: "/yr",
    progress: 58,
    verified: true,
    gradient: "from-indigo-400 to-purple-600",
    tags: ["Terraced", "2 Bed"],
  },
  {
    id: 7,
    title: "8VX",
    subtitle: "#MNBVCXZ",
    price: "£5,200.00",
    pricePeriod: "/yr",
    progress: 25,
    verified: true,
    gradient: "from-violet-600 to-fuchsia-700",
    description:
      "Semi-detached family home on a quiet cul-de-sac. Large rear garden with mature trees, double garage, and recently extended conservatory.",
    tags: ["Semi-Detached", "Garage", "Quiet"],
  },
];
